spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userservicedb
    driver-class-name: org.postgresql.Driver
    username: securebank
    password: securebank123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect